using PortfolioWebPlatform.EntityFrameworkCore;
using Xunit;

namespace PortfolioWebPlatform.EntityFrameworkCore;

public class PortfolioWebPlatformEntityFrameworkCoreCollectionFixtureBase : ICollectionFixture<PortfolioWebPlatformEntityFrameworkCoreFixture>
{

}
